import "./globals.css";
// import { Oswald } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
// import Main from "./pages/Main";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const inter = Oswald({ subsets: ["latin"] });
// eslint-disable-next-line react/prop-types
export default function RootLayout({ children }) {
  console.log(children);
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Jost:wght@800&family=Oswald:wght@400;500&family=Roboto+Condensed:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
